import {
  Card,
  BASIC_ELEMENTS,
  HYBRID_ELEMENTS,
  TIMING,
  CARD_TYPES,
} from "../types/card";

// Card data for Algomancy cards
// This file is auto-generated by the card entry helper
// Do not edit this file directly
export const algomancyCards: Card[] = [
  {
    "id": "cinder-scuttler",
    "name": "Cinder Scuttler",
    "manaCost": 1,
    "element": {
      "type": BASIC_ELEMENTS.FIRE,
      "symbol": "/images/elements/fire.png"
    },
    "stats": {
      "power": 2,
      "defense": 1,
      "affinity": {
        "fire": 1
      }
    },
    "timing": {
      "type": TIMING.HASTE,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Infernal Insect",
      "attributes": []
    },
    "abilities": [
      "When you deal combat damage to an opponent, if I am in your bin, recall me. (Put me into your hand.)"
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747594772/algomancy/cards/algomancy_cinder-scuttler.jpg",
    "currentIndex": 54
  },
  {
    "id": "a-fast-pile-of-rocks",
    "name": "A Fast Pile of Rocks",
    "manaCost": 2,
    "element": {
      "type": BASIC_ELEMENTS.EARTH,
      "symbol": "/images/elements/earth.png"
    },
    "stats": {
      "power": 2,
      "defense": 1,
      "affinity": {
        "earth": 1
      }
    },
    "timing": {
      "type": TIMING.HASTE,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Rock Pile",
      "attributes": []
    },
    "abilities": [
      "When I die, GRAFT Rockfall 4. (Each player chooses one of their units. I deal 4 damage to each of the chosen units.)"
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "/images/cards/a-fast-pile-of-rocks.jpg",
    "currentIndex": 0
  },
  {
    "id": "a-pile-of-rubbish",
    "name": "A Pile of Rubbish",
    "manaCost": 2,
    "element": {
      "type": BASIC_ELEMENTS.METAL,
      "symbol": "/images/elements/metal.png"
    },
    "stats": {
      "power": 1,
      "defense": 1,
      "affinity": {
        "metal": 1
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Scrap Pile Unit",
      "attributes": []
    },
    "abilities": [
      "AUGMENT When I die, draw a card."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "/images/cards/a-pile-of-rubbish.jpg",
    "currentIndex": 1
  },
  {
    "id": "a-pile-of-runes",
    "name": "A Pile of Runes",
    "manaCost": 3,
    "element": {
      "type": HYBRID_ELEMENTS.EARTH_WATER,
      "symbol": "/images/elements/earth.png",
      "secondarySymbol": "/images/elements/water.png"
    },
    "stats": {
      "power": 1,
      "defense": 3,
      "affinity": {
        "water": 1,
        "earth": 1
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Mystic Primordial Pile",
      "attributes": []
    },
    "abilities": [
      "AUGMENT: When I despawn, create a Crystal X, where X is my defense."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747595250/algomancy/cards/algomancy_a-pile-of-runes.jpg",
    "currentIndex": 2
  },
  {
    "id": "abduct",
    "name": "Abduct",
    "manaCost": 0,
    "element": {
      "type": HYBRID_ELEMENTS.METAL_WOOD,
      "symbol": "/images/elements/metal.png",
      "secondarySymbol": "/images/elements/wood.png"
    },
    "stats": {
      "power": 0,
      "defense": 0,
      "affinity": {
        "wood": 1,
        "metal": 1
      }
    },
    "timing": {
      "type": TIMING.BATTLE,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.SPELL,
      "subType": "Alien",
      "attributes": []
    },
    "abilities": [
      "Gain control of target unit with cost X or less unless its controller pays X."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Rare"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747595542/algomancy/cards/algomancy_abduct.jpg",
    "currentIndex": 3
  },
  {
    "id": "aberrant-populace",
    "name": "Aberrant Populace",
    "manaCost": 2,
    "element": {
      "type": BASIC_ELEMENTS.FIRE,
      "symbol": "/images/elements/fire.png"
    },
    "stats": {
      "power": 1,
      "defense": 1,
      "affinity": {
        "fire": 2
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Spirit Horror",
      "attributes": []
    },
    "abilities": [
      "When I attack, block, or die, GRAFT1: Create two Wisps. (They aren't in formation.)"
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747595589/algomancy/cards/algomancy_aberrant-populace.jpg",
    "currentIndex": 4
  },
  {
    "id": "aberrant-statweaver",
    "name": "Aberrant Statweaver",
    "manaCost": 3,
    "element": {
      "type": BASIC_ELEMENTS.METAL,
      "symbol": "/images/elements/metal.png"
    },
    "stats": {
      "power": 3,
      "defense": 3,
      "affinity": {
        "metal": 2
      }
    },
    "timing": {
      "type": TIMING.VIRUS,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Unstable Luminary Unit",
      "attributes": [
        "Unstable"
      ]
    },
    "abilities": [
      "(If an unstable card would enter a bin from and active zone, erase it instead.)",
      "AUGMENT: Your units are base 3/3."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Rare"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747595685/algomancy/cards/algomancy_aberrant-statweaver.jpg",
    "currentIndex": 5
  },
  {
    "id": "abyssal-evocation",
    "name": "Abyssal Evocation",
    "manaCost": 4,
    "element": {
      "type": BASIC_ELEMENTS.FIRE,
      "symbol": "/images/elements/fire.png"
    },
    "stats": {
      "power": 0,
      "defense": 0,
      "affinity": {
        "fire": 2
      }
    },
    "timing": {
      "type": TIMING.BATTLE,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.SPELL,
      "subType": "Arcane Occult",
      "attributes": []
    },
    "abilities": [
      "In this battle, you may play spells from your bin. If you do, they gain unstable until regroup. (If they would enter a bin, erase them instead.)"
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Rare"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747595735/algomancy/cards/algomancy_abyssal-evocation.jpg",
    "currentIndex": 6
  },
  {
    "id": "accelerated-germination",
    "name": "Accelerated Germination",
    "manaCost": 2,
    "element": {
      "type": BASIC_ELEMENTS.WOOD,
      "symbol": "/images/elements/wood.png"
    },
    "stats": {
      "power": 0,
      "defense": 0,
      "affinity": {
        "wood": 2
      }
    },
    "timing": {
      "type": TIMING.HASTE,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.SPELL,
      "subType": "Flower",
      "attributes": []
    },
    "abilities": [
      "GRAFT1: Create two 1/1 units."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747595761/algomancy/cards/algomancy_accelerated-germination.jpg",
    "currentIndex": 7
  },
  {
    "id": "accumulated-nucleation",
    "name": "Accumulated Nucleation",
    "manaCost": 2,
    "element": {
      "type": BASIC_ELEMENTS.EARTH,
      "symbol": "/images/elements/earth.png"
    },
    "stats": {
      "power": 0,
      "defense": 0,
      "affinity": {
        "earth": 1
      }
    },
    "timing": {
      "type": TIMING.BATTLE,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.SPELL,
      "subType": "Mystic Elemental",
      "attributes": []
    },
    "abilities": [
      "Put a +1/+1 counter on target unit for each of your EARTH resources."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747595796/algomancy/cards/algomancy_accumulated-nucleation.jpg",
    "currentIndex": 8
  },
  {
    "id": "adversary-of-the-deep",
    "name": "Adversary of the Deep",
    "manaCost": 4,
    "element": {
      "type": HYBRID_ELEMENTS.METAL_WATER,
      "symbol": "/images/elements/metal.png",
      "secondarySymbol": "/images/elements/water.png"
    },
    "stats": {
      "power": 2,
      "defense": 2,
      "affinity": {
        "water": 1,
        "metal": 1
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Sluggish Jellyfish",
      "attributes": [
        "Sluggish"
      ]
    },
    "abilities": [
      "(Sluggish units deal combat damage last.)",
      "AUGMENT: Whenever a player loses life, put that many +1/+1 counters on me. (Damage causes life loss.)"
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Rare"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747595864/algomancy/cards/algomancy_adversary-of-the-deep.jpg",
    "currentIndex": 9
  },
  {
    "id": "aether-channeler",
    "name": "Aether Channeler",
    "manaCost": 2,
    "element": {
      "type": HYBRID_ELEMENTS.EARTH_WOOD,
      "symbol": "/images/elements/earth.png",
      "secondarySymbol": "/images/elements/wood.png"
    },
    "stats": {
      "power": 2,
      "defense": 3,
      "affinity": {
        "earth": 1,
        "wood": 1
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Plant Primordial",
      "attributes": []
    },
    "abilities": [
      "AUGMENT: Whenever another nontoken ally spawns, create a Crystal 1."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747595904/algomancy/cards/algomancy_aether-channeler.jpg",
    "currentIndex": 10
  },
  {
    "id": "aethercap-siphoner",
    "name": "Aethercap Siphoner",
    "manaCost": 3,
    "element": {
      "type": HYBRID_ELEMENTS.WOOD_WATER,
      "symbol": "/images/elements/wood.png",
      "secondarySymbol": "/images/elements/water.png"
    },
    "stats": {
      "power": 4,
      "defense": 4,
      "affinity": {
        "water": 1,
        "wood": 1
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Cosmic Fungus Blight",
      "attributes": []
    },
    "abilities": [
      "I spawn with three -1/-1 counters on me.",
      "AUGMENT: Whenever you play a nontoken spell, you may move a counter from me onto another target unit."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Rare"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747595966/algomancy/cards/algomancy_aethercap-siphoner.jpg",
    "currentIndex": 11
  },
  {
    "id": "aetherflux-golem",
    "name": "Aetherflux Golem",
    "manaCost": 1,
    "element": {
      "type": BASIC_ELEMENTS.EARTH,
      "symbol": "/images/elements/earth.png"
    },
    "stats": {
      "power": 1,
      "defense": 1,
      "affinity": {
        "earth": 2
      }
    },
    "timing": {
      "type": TIMING.VIRUS,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Golem Sprite",
      "attributes": []
    },
    "abilities": [
      "AUGMENT: I gain +2/+2."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747595990/algomancy/cards/algomancy_aetherflux-golem.jpg",
    "currentIndex": 12
  },
  {
    "id": "all-consuming-blaze",
    "name": "All-Consuming Blaze",
    "manaCost": 2,
    "element": {
      "type": BASIC_ELEMENTS.FIRE,
      "symbol": "/images/elements/fire.png"
    },
    "stats": {
      "power": 0,
      "defense": 0,
      "affinity": {
        "fire": 1
      }
    },
    "timing": {
      "type": TIMING.BATTLE,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.SPELL,
      "subType": "Elemental",
      "attributes": []
    },
    "abilities": [
      "I deal damage to any target equal to you FIRE resources."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747596017/algomancy/cards/algomancy_all-consuming-blaze.jpg",
    "currentIndex": 13
  },
  {
    "id": "all-consuming-blight",
    "name": "All-Consuming Blight",
    "manaCost": 4,
    "element": {
      "type": BASIC_ELEMENTS.WOOD,
      "symbol": "/images/elements/wood.png"
    },
    "stats": {
      "power": 0,
      "defense": 0,
      "affinity": {
        "wood": 2
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.SPELL,
      "subType": "Ancient Blight",
      "attributes": []
    },
    "abilities": [
      "Create a Poison 1 for each of your units."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Rare"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747596049/algomancy/cards/algomancy_all-consuming-blight.jpg",
    "currentIndex": 14
  },
  {
    "id": "ambling-mountaintop",
    "name": "Ambling Mountaintop",
    "manaCost": 2,
    "element": {
      "type": BASIC_ELEMENTS.EARTH,
      "symbol": "/images/elements/earth.png"
    },
    "stats": {
      "power": 4,
      "defense": 5,
      "affinity": {
        "earth": 2
      }
    },
    "timing": {
      "type": TIMING.VIRUS,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "AUGMENT Sluggish Rock Beast",
      "attributes": [
        "Sluggish"
      ]
    },
    "abilities": [
      "(Sluggish units deal combat damage last.)"
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747596086/algomancy/cards/algomancy_ambling-mountaintop.jpg",
    "currentIndex": 15
  },
  {
    "id": "amphivore",
    "name": "Amphivore",
    "manaCost": 4,
    "element": {
      "type": BASIC_ELEMENTS.WATER,
      "symbol": "/images/elements/water.png"
    },
    "stats": {
      "power": 2,
      "defense": 5,
      "affinity": {
        "water": 1
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Frog Beast",
      "attributes": []
    },
    "abilities": [
      "When my column deals combat damage to an opponent, GRAFT1,GRAFT1,GRAFT1 (Trigger three copies of this graft ability as one single trigger)."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Rare"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747596147/algomancy/cards/algomancy_amphivore.jpg",
    "currentIndex": 16
  },
  {
    "id": "ancient-one",
    "name": "Ancient One",
    "manaCost": 2,
    "element": {
      "type": BASIC_ELEMENTS.METAL,
      "symbol": "/images/elements/metal.png"
    },
    "stats": {
      "power": 1,
      "defense": 1,
      "affinity": {
        "metal": 2
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Ancient Mimic",
      "attributes": []
    },
    "abilities": [
      "AUGMENT: I have all abilities of adjacent allies. (This includes modded abilities.)"
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Rare"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747596189/algomancy/cards/algomancy_ancient-one.jpg",
    "currentIndex": 17
  },
  {
    "id": "animated-spark",
    "name": "Animated Spark",
    "manaCost": 1,
    "element": {
      "type": BASIC_ELEMENTS.FIRE,
      "symbol": "/images/elements/fire.png"
    },
    "stats": {
      "power": 0,
      "defense": 1,
      "affinity": {
        "fire": 1
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Anima",
      "attributes": []
    },
    "abilities": [
      "AUGMENT: Your units gain +1/+0 for each nontoken spell you've played in this battle."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Rare"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747596257/algomancy/cards/algomancy_animated-spark.jpg",
    "currentIndex": 18
  },
  {
    "id": "arc-lightning",
    "name": "Arc Lightning",
    "manaCost": 4,
    "element": {
      "type": BASIC_ELEMENTS.FIRE,
      "symbol": "/images/elements/fire.png"
    },
    "stats": {
      "power": 0,
      "defense": 0,
      "affinity": {
        "fire": 2
      }
    },
    "timing": {
      "type": TIMING.BATTLE,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.SPELL,
      "subType": "Electric Elemental",
      "attributes": [
        "Electric"
      ]
    },
    "abilities": [
      "(Excess damage from electric sources can be directed to an adjacent unit, recursively.)",
      "I deal 6 damage to any target."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747596320/algomancy/cards/algomancy_arc-lightning.jpg",
    "currentIndex": 19
  },
  {
    "id": "arcane-concentrator",
    "name": "Arcane Concentrator",
    "manaCost": 3,
    "element": {
      "type": BASIC_ELEMENTS.WATER,
      "symbol": "/images/elements/water.png"
    },
    "stats": {
      "power": 3,
      "defense": 2,
      "affinity": {
        "water": 2
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Arcane Alien",
      "attributes": []
    },
    "abilities": [
      "AUGMENT 1X: When you play a nontoken spell, create an X/X unit, where X is the spell's cost."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747596367/algomancy/cards/algomancy_arcane-concentrator.jpg",
    "currentIndex": 20
  },
  {
    "id": "arcane-echo",
    "name": "Arcane Echo",
    "manaCost": 2,
    "element": {
      "type": BASIC_ELEMENTS.METAL,
      "symbol": "/images/elements/metal.png"
    },
    "stats": {
      "power": 0,
      "defense": 0,
      "affinity": {
        "metal": 1
      }
    },
    "timing": {
      "type": TIMING.BATTLE,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.SPELL,
      "subType": "Arcane Mimic",
      "attributes": []
    },
    "abilities": [
      "GRAFT1: Create a copy of target token."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Rare"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747596400/algomancy/cards/algomancy_arcane-echo.jpg",
    "currentIndex": 21
  },
  {
    "id": "astral-painseeker",
    "name": "Astral Painseeker",
    "manaCost": 5,
    "element": {
      "type": HYBRID_ELEMENTS.FIRE_WATER,
      "symbol": "/images/elements/fire.png",
      "secondarySymbol": "/images/elements/water.png"
    },
    "stats": {
      "power": 3,
      "defense": 3,
      "affinity": {
        "fire": 1,
        "water": 1
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Cosmic Elemental",
      "attributes": []
    },
    "abilities": [
      "When a player loses life during battle, GRAFT1 Draw a card. (Damage causes life loss.)"
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747596445/algomancy/cards/algomancy_astral-painseeker.jpg",
    "currentIndex": 22
  },
  {
    "id": "astral-tidewraith",
    "name": "Astral Tidewraith",
    "manaCost": 3,
    "element": {
      "type": BASIC_ELEMENTS.WATER,
      "symbol": "/images/elements/water.png"
    },
    "stats": {
      "power": 0,
      "defense": 6,
      "affinity": {
        "water": 2
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Spirit Jellyfish",
      "attributes": []
    },
    "abilities": [
      "When I attack or block, GRAFT1 I deal damage to each player equal to the number of cards in their hand."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747596483/algomancy/cards/algomancy_astral-tidewraith.jpg",
    "currentIndex": 23
  },
  {
    "id": "astralith",
    "name": "Astralith",
    "manaCost": 1,
    "element": {
      "type": BASIC_ELEMENTS.METAL,
      "symbol": "/images/elements/metal.png"
    },
    "stats": {
      "power": 2,
      "defense": 3,
      "affinity": {
        "metal": 1
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Polyform Scrap",
      "attributes": []
    },
    "abilities": [
      "AUGMENT/3: Put a +1/+1 counter on target unit."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747596516/algomancy/cards/algomancy_astralith.jpg",
    "currentIndex": 24
  },
  {
    "id": "auric-ascendant",
    "name": "Auric Ascendant",
    "manaCost": 2,
    "element": {
      "type": HYBRID_ELEMENTS.METAL_WATER,
      "symbol": "/images/elements/metal.png",
      "secondarySymbol": "/images/elements/water.png"
    },
    "stats": {
      "power": 2,
      "defense": 1,
      "affinity": {
        "water": 1,
        "metal": 1
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Mystic Avatar",
      "attributes": []
    },
    "abilities": [
      "1x 1, Recall another ally: I gain flying and +2/+0 until regroup. (Only flying units can block flying units.)"
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Rare"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747596585/algomancy/cards/algomancy_auric-ascendant.jpg",
    "currentIndex": 25
  },
  {
    "id": "automaton-of-abundance",
    "name": "Automaton of Abundance",
    "manaCost": 5,
    "element": {
      "type": BASIC_ELEMENTS.METAL,
      "symbol": "/images/elements/metal.png"
    },
    "stats": {
      "power": 2,
      "defense": 6,
      "affinity": {
        "metal": 2
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Automaton Construct",
      "attributes": []
    },
    "abilities": [
      "AUGMENT: If you would create one or more unit tokens, instead create those tokens plus an additional copy of each unique token you created."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Rare"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747596639/algomancy/cards/algomancy_automaton-of-abundance.jpg",
    "currentIndex": 26
  },
  {
    "id": "awoken-tomb",
    "name": "Awoken Tomb",
    "manaCost": 3,
    "element": {
      "type": BASIC_ELEMENTS.EARTH,
      "symbol": "/images/elements/earth.png"
    },
    "stats": {
      "power": 0,
      "defense": 5,
      "affinity": {
        "earth": 2
      }
    },
    "timing": {
      "type": TIMING.HASTE,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Rock Structure",
      "attributes": []
    },
    "abilities": [
      "AUGMENT 1x: When I am dealt damage, create X/X unit, where X is the damage I am dealt. "
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747596686/algomancy/cards/algomancy_awoken-tomb.jpg",
    "currentIndex": 27
  },
  {
    "id": "battle",
    "name": "Battle",
    "manaCost": 4,
    "element": {
      "type": BASIC_ELEMENTS.EARTH,
      "symbol": "/images/elements/earth.png"
    },
    "stats": {
      "power": 0,
      "defense": 0,
      "affinity": {
        "earth": 2
      }
    },
    "timing": {
      "type": TIMING.BATTLE,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.SPELL,
      "subType": "Bedlam",
      "attributes": []
    },
    "abilities": [
      "Two target units fight. (They deal damage to each other equal to their power.)"
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747596725/algomancy/cards/algomancy_battle.jpg",
    "currentIndex": 28
  },
  {
    "id": "bellowing-boulder",
    "name": "Bellowing Boulder",
    "manaCost": 4,
    "element": {
      "type": BASIC_ELEMENTS.EARTH,
      "symbol": "/images/elements/earth.png"
    },
    "stats": {
      "power": 3,
      "defense": 4,
      "affinity": {
        "earth": 1
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Beast Rock Structure",
      "attributes": []
    },
    "abilities": [
      "When I attack or block, GRAFT: I deal 1 damage to each unit."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747596755/algomancy/cards/algomancy_bellowing-boulder.jpg",
    "currentIndex": 29
  },
  {
    "id": "biomass-devourer",
    "name": "Biomass Devourer",
    "manaCost": 2,
    "element": {
      "type": BASIC_ELEMENTS.METAL,
      "symbol": "/images/elements/metal.png"
    },
    "stats": {
      "power": 3,
      "defense": 2,
      "affinity": {
        "metal": 1
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Alien Robot",
      "attributes": []
    },
    "abilities": [
      "AUGMENT: Whenever a nontoken unit dies, you may pay 2 to erase it and put two +1/+1 counters on me."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Rare"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747596808/algomancy/cards/algomancy_biomass-devourer.jpg",
    "currentIndex": 30
  },
  {
    "id": "bioremediation",
    "name": "Bioremediation",
    "manaCost": 4,
    "element": {
      "type": BASIC_ELEMENTS.WOOD,
      "symbol": "/images/elements/wood.png"
    },
    "stats": {
      "power": 0,
      "defense": 0,
      "affinity": {
        "wood": 3
      }
    },
    "timing": {
      "type": TIMING.BATTLE,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.SPELL,
      "subType": "Fungus",
      "attributes": []
    },
    "abilities": [
      "Target player reveals their hand. You choose a card from it and put it into your hand."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747596846/algomancy/cards/algomancy_bioremediation.jpg",
    "currentIndex": 31
  },
  {
    "id": "biotoxicity",
    "name": "Biotoxicity",
    "manaCost": 2,
    "element": {
      "type": BASIC_ELEMENTS.WOOD,
      "symbol": "/images/elements/wood.png"
    },
    "stats": {
      "power": 0,
      "defense": 0,
      "affinity": {
        "wood": 1
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.SPELL,
      "subType": "Arcame Blight",
      "attributes": []
    },
    "abilities": [
      "GRAFT1: Create three Poison 1. "
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747596951/algomancy/cards/algomancy_biotoxicity.jpg",
    "currentIndex": 32
  },
  {
    "id": "bloated-manablub",
    "name": "Bloated Manablub",
    "manaCost": 1,
    "element": {
      "type": BASIC_ELEMENTS.WATER,
      "symbol": "/images/elements/water.png"
    },
    "stats": {
      "power": 2,
      "defense": 1,
      "affinity": {
        "water": 1
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Cloud Manatee",
      "attributes": []
    },
    "abilities": [
      "When I despawn, GRAFT1: Each opponent loses 3 life."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747597017/algomancy/cards/algomancy_bloated-manablub.jpg",
    "currentIndex": 33
  },
  {
    "id": "bloodwind-revenant",
    "name": "Bloodwind Revenant",
    "manaCost": 2,
    "element": {
      "type": BASIC_ELEMENTS.FIRE,
      "symbol": "/images/elements/fire.png"
    },
    "stats": {
      "power": 1,
      "defense": 2,
      "affinity": {
        "fire": 1
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Flying Occult Spirit",
      "attributes": [
        "Flying"
      ]
    },
    "abilities": [
      "(Only flying units can block flying units.)",
      "When my column deals combat damage to an opponent, GRAFT1: You may sacrifice a unit. If you do, draw a card. "
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Rare"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747597085/algomancy/cards/algomancy_bloodwind-revenant.jpg",
    "currentIndex": 34
  },
  {
    "id": "bloomcaster",
    "name": "Bloomcaster",
    "manaCost": 2,
    "element": {
      "type": BASIC_ELEMENTS.WOOD,
      "symbol": "/images/elements/wood.png"
    },
    "stats": {
      "power": 2,
      "defense": 2,
      "affinity": {
        "wood": 2
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Druid Flower",
      "attributes": []
    },
    "abilities": [
      "AUGMENT: Whenever you play a unit, create a 1/1 unit."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747597119/algomancy/cards/algomancy_bloomcaster.jpg",
    "currentIndex": 35
  },
  {
    "id": "body-swap",
    "name": "Body Swap",
    "manaCost": 2,
    "element": {
      "type": BASIC_ELEMENTS.METAL,
      "symbol": "/images/elements/metal.png"
    },
    "stats": {
      "power": 0,
      "defense": 0,
      "affinity": {
        "metal": 1
      }
    },
    "timing": {
      "type": TIMING.BATTLE,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.SPELL,
      "subType": "Arcane",
      "attributes": []
    },
    "abilities": [
      "GRAFT1: Exchange the base stats of two target units until regroup. (With each other.)"
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Rare"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747597161/algomancy/cards/algomancy_body-swap.jpg",
    "currentIndex": 36
  },
  {
    "id": "boon-of-protection",
    "name": "Boon of Protection",
    "manaCost": 1,
    "element": {
      "type": BASIC_ELEMENTS.WOOD,
      "symbol": "/images/elements/wood.png"
    },
    "stats": {
      "power": 0,
      "defense": 0,
      "affinity": {
        "wood": 2
      }
    },
    "timing": {
      "type": TIMING.BATTLE,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.SPELL,
      "subType": "Druid",
      "attributes": []
    },
    "abilities": [
      "Negate target effect that targets an allied effect, player or unit."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747597201/algomancy/cards/algomancy_boon-of-protection.jpg",
    "currentIndex": 37
  },
  {
    "id": "boreal-wanderer",
    "name": "Boreal Wanderer",
    "manaCost": 2,
    "element": {
      "type": BASIC_ELEMENTS.WATER,
      "symbol": "/images/elements/water.png"
    },
    "stats": {
      "power": 2,
      "defense": 2,
      "affinity": {
        "water": 1
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Alien Beast",
      "attributes": []
    },
    "abilities": [
      "When another ally spawns during battle, GRAFT1: I deal 2 damage to each opponent."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747597234/algomancy/cards/algomancy_boreal-wanderer.jpg",
    "currentIndex": 38
  },
  {
    "id": "borrower-of-forms",
    "name": "Borrower of Forms",
    "manaCost": 7,
    "element": {
      "type": BASIC_ELEMENTS.METAL,
      "symbol": "/images/elements/metal.png"
    },
    "stats": {
      "power": 2,
      "defense": 2,
      "affinity": {
        "metal": 3
      }
    },
    "timing": {
      "type": TIMING.BATTLE,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.SPELL_UNIT,
      "subType": "Squid Mimic",
      "attributes": []
    },
    "abilities": [
      "Erase target unit. I become an exact copy of that unit. (I copy all stat changes, counters, card text and mods.)"
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Rare"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747597282/algomancy/cards/algomancy_borrower-of-forms.jpg",
    "currentIndex": 39
  },
  {
    "id": "bripp",
    "name": "Bripp",
    "manaCost": 3,
    "element": {
      "type": BASIC_ELEMENTS.WATER,
      "symbol": "/images/elements/water.png"
    },
    "stats": {
      "power": 4,
      "defense": 2,
      "affinity": {
        "water": 2
      }
    },
    "timing": {
      "type": TIMING.BATTLE,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.SPELL_UNIT,
      "subType": "Feeble Jellyfish Cloud",
      "attributes": [
        "Feeble"
      ]
    },
    "abilities": [
      "(Feeble units can't block.)",
      "GRAFT1: Look at target player's hand. You may choose a card from it and recycle that card. If you do, that player draws a card."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Rare"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747597349/algomancy/cards/algomancy_bripp.jpg",
    "currentIndex": 40
  },
  {
    "id": "bubb",
    "name": "Bubb",
    "manaCost": 4,
    "element": {
      "type": BASIC_ELEMENTS.EARTH,
      "symbol": "/images/elements/earth.png"
    },
    "stats": {
      "power": 5,
      "defense": 6,
      "affinity": {
        "earth": 1
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "AUGMENT Unaware Druid Rock Turtle",
      "attributes": [
        "Unaware"
      ]
    },
    "abilities": [
      "(Unaware cards and units they are interacting with ignore all stat changes.)"
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747597390/algomancy/cards/algomancy_bubb.jpg",
    "currentIndex": 41
  },
  {
    "id": "bumblecrab",
    "name": "Bumblecrab",
    "manaCost": 1,
    "element": {
      "type": BASIC_ELEMENTS.EARTH,
      "symbol": "/images/elements/earth.png"
    },
    "stats": {
      "power": 2,
      "defense": 3,
      "affinity": {
        "earth": 2
      }
    },
    "timing": {
      "type": TIMING.VIRUS,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "AUGMENT Piercing Insect Crab",
      "attributes": [
        "Piercing"
      ]
    },
    "abilities": [
      "(Excess damage from piercing sources is dealt to the recipient's controller.)"
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747597435/algomancy/cards/algomancy_bumblecrab.jpg",
    "currentIndex": 42
  },
  {
    "id": "burgeon",
    "name": "Burgeon",
    "manaCost": 2,
    "element": {
      "type": BASIC_ELEMENTS.WOOD,
      "symbol": "/images/elements/wood.png"
    },
    "stats": {
      "power": 0,
      "defense": 0,
      "affinity": {
        "wood": 1
      }
    },
    "timing": {
      "type": TIMING.BATTLE,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.SPELL,
      "subType": "Druid",
      "attributes": []
    },
    "abilities": [
      "GRAFT1: Double the [power or defense] of target unit until regroup."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747597472/algomancy/cards/algomancy_burgeon.jpg",
    "currentIndex": 43
  },
  {
    "id": "burning-vengeance",
    "name": "Burning Vengeance",
    "manaCost": 1,
    "element": {
      "type": BASIC_ELEMENTS.FIRE,
      "symbol": "/images/elements/fire.png"
    },
    "stats": {
      "power": 0,
      "defense": 0,
      "affinity": {
        "fire": 1
      }
    },
    "timing": {
      "type": TIMING.BATTLE,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.SPELL,
      "subType": "Infernal Occult",
      "attributes": []
    },
    "abilities": [
      "GRAFT1: I deal damage to any target equal to the number of units that died in this battle."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747597505/algomancy/cards/algomancy_burning-vengeance.jpg",
    "currentIndex": 44
  },
  {
    "id": "carapace-devourer",
    "name": "Carapace Devourer",
    "manaCost": 2,
    "element": {
      "type": BASIC_ELEMENTS.EARTH,
      "symbol": "/images/elements/earth.png"
    },
    "stats": {
      "power": 3,
      "defense": 3,
      "affinity": {
        "earth": 1
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "AUGMENT Deadly Bedlam Beast",
      "attributes": [
        "Deadly"
      ]
    },
    "abilities": [
      "(Any damage from a deadly source will kill a unit.)"
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747597541/algomancy/cards/algomancy_carapace-devourer.jpg",
    "currentIndex": 45
  },
  {
    "id": "celestial-fluxmorph",
    "name": "Celestial Fluxmorph",
    "manaCost": 2,
    "element": {
      "type": BASIC_ELEMENTS.METAL,
      "symbol": "/images/elements/metal.png"
    },
    "stats": {
      "power": 1,
      "defense": 1,
      "affinity": {
        "metal": 1
      }
    },
    "timing": {
      "type": TIMING.VIRUS,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Cosmic Spirit",
      "attributes": []
    },
    "abilities": [
      "When I spawn or become modded, put a +1/+1 counter on each of your units. AUGMENT: When I despawn, remove all counters from you units."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Rare"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747597593/algomancy/cards/algomancy_celestial-fluxmorph.jpg",
    "currentIndex": 46
  },
  {
    "id": "celestial-purge",
    "name": "Celestial Purge",
    "manaCost": 1,
    "element": {
      "type": BASIC_ELEMENTS.WATER,
      "symbol": "/images/elements/water.png"
    },
    "stats": {
      "power": 0,
      "defense": 0,
      "affinity": {
        "water": 2
      }
    },
    "timing": {
      "type": TIMING.BATTLE,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.SPELL,
      "subType": "Cosmic",
      "attributes": []
    },
    "abilities": [
      "Erase target unit. Its controller Glimpses 3. (They reveal the top three cards of thei deck and cache one. Until end of the turn, they may play it as if it was in their hand, ignoring affinity. Recycle the rest.)"
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Rare"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747597661/algomancy/cards/algomancy_celestial-purge.jpg",
    "currentIndex": 47
  },
  {
    "id": "celestial-shifter",
    "name": "Celestial Shifter",
    "manaCost": 2,
    "element": {
      "type": BASIC_ELEMENTS.METAL,
      "symbol": "/images/elements/metal.png"
    },
    "stats": {
      "power": 2,
      "defense": 2,
      "affinity": {
        "metal": 1
      }
    },
    "timing": {
      "type": TIMING.HASTE,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Cosmic Alien",
      "attributes": []
    },
    "abilities": [
      "AUGMENT X: I become base X/X until regroup."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747597691/algomancy/cards/algomancy_celestial-shifter.jpg",
    "currentIndex": 48
  },
  {
    "id": "channel-through",
    "name": "Channel Through",
    "manaCost": 0,
    "element": {
      "type": HYBRID_ELEMENTS.EARTH_FIRE,
      "symbol": "/images/elements/earth.png",
      "secondarySymbol": "/images/elements/fire.png"
    },
    "stats": {
      "power": 0,
      "defense": 0,
      "affinity": {
        "fire": 1,
        "earth": 2
      }
    },
    "timing": {
      "type": TIMING.BATTLE,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.SPELL,
      "subType": "Elemental",
      "attributes": []
    },
    "abilities": [
      "I deal 2 damage to each of X target allies. For each ally damaged this way, distribute 2 damage among target opponent's units. "
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Rare"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747597738/algomancy/cards/algomancy_channel-through.jpg",
    "currentIndex": 49
  },
  {
    "id": "channeled-amalgam",
    "name": "Channeled Amalgam",
    "manaCost": 2,
    "element": {
      "type": BASIC_ELEMENTS.WATER,
      "symbol": "/images/elements/water.png"
    },
    "stats": {
      "power": 1,
      "defense": 1,
      "affinity": {
        "water": 2
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Polyform Anima",
      "attributes": []
    },
    "abilities": [
      "AUGMENT 1X: When you play a nontoken spell, put X +1/+1 counters on me, where X is that spell's cost."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747597779/algomancy/cards/algomancy_channeled-amalgam.jpg",
    "currentIndex": 50
  },
  {
    "id": "channeled-boon",
    "name": "Channeled Boon",
    "manaCost": 2,
    "element": {
      "type": BASIC_ELEMENTS.FIRE,
      "symbol": "/images/elements/fire.png"
    },
    "stats": {
      "power": 0,
      "defense": 0,
      "affinity": {
        "fire": 1
      }
    },
    "timing": {
      "type": TIMING.BATTLE,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.SPELL,
      "subType": "Elemental",
      "attributes": []
    },
    "abilities": [
      "GRAFT: Target unit gains +4/+4 until regroup."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747597808/algomancy/cards/algomancy_channeled-boon.jpg",
    "currentIndex": 51
  },
  {
    "id": "child-of-aether",
    "name": "Child of Aether",
    "manaCost": 1,
    "element": {
      "type": BASIC_ELEMENTS.EARTH,
      "symbol": "/images/elements/earth.png"
    },
    "stats": {
      "power": 2,
      "defense": 0,
      "affinity": {
        "earth": 1
      }
    },
    "timing": {
      "type": TIMING.VIRUS,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "AUGMENT Balanced Ancient Druid",
      "attributes": [
        "Balanced"
      ]
    },
    "abilities": [
      "(The power and defense of balanced units are equal to the greater of the two,)"
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Rare"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747597852/algomancy/cards/algomancy_child-of-aether.jpg",
    "currentIndex": 52
  },
  {
    "id": "chitin-shredder",
    "name": "Chitin Shredder",
    "manaCost": 2,
    "element": {
      "type": BASIC_ELEMENTS.EARTH,
      "symbol": "/images/elements/earth.png"
    },
    "stats": {
      "power": 1,
      "defense": 2,
      "affinity": {
        "earth": 2
      }
    },
    "timing": {
      "type": TIMING.VIRUS,
      "description": "Special timing rules apply"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "AUGMENT Powerful Insect Unit",
      "attributes": [
        "Powerful"
      ]
    },
    "abilities": [
      "(Powerful sources deal double damage.)"
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747597887/algomancy/cards/algomancy_chitin-shredder.jpg",
    "currentIndex": 53
  },
  {
    "id": "collective-creation",
    "name": "Collective Creation",
    "manaCost": 10,
    "element": {
      "type": BASIC_ELEMENTS.COLORLESS,
      "symbol": "/images/elements/colorless.png"
    },
    "stats": {
      "power": 4046,
      "defense": 4046,
      "affinity": {}
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.UNIT,
      "subType": "Cosmic Glitch",
      "attributes": []
    },
    "abilities": [],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Mythic"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747597918/algomancy/cards/algomancy_collective-creation.jpg",
    "currentIndex": 55
  },
  {
    "id": "colossal-construction",
    "name": "Colossal Construction",
    "manaCost": 3,
    "element": {
      "type": HYBRID_ELEMENTS.METAL_EARTH,
      "symbol": "/images/elements/metal.png",
      "secondarySymbol": "/images/elements/earth.png"
    },
    "stats": {
      "power": 0,
      "defense": 0,
      "affinity": {
        "earth": 1,
        "metal": 1
      }
    },
    "timing": {
      "type": TIMING.STANDARD,
      "description": "Can be played during deployment"
    },
    "typeAndAttributes": {
      "mainType": CARD_TYPES.SPELL,
      "subType": "Primordial Technology",
      "attributes": []
    },
    "abilities": [
      "GRAFT1: Create a Robot X, where X is the greatest defense among your units."
    ],
    "set": {
      "symbol": "core",
      "name": "Core Set",
      "complexity": "Common"
    },
    "imageUrl": "https://res.cloudinary.com/dyfj9qvc0/image/upload/v1747597963/algomancy/cards/algomancy_colossal-construction.jpg",
    "currentIndex": 56
  }
];
